### PR TITLE
Create class-wpsms-gateway-smsdone.php

### PR DESCRIPTION
**Pull request by ismailh**
SMS Done Gateway
Only Work for Bangladesh
https://smsd.one/

### CODE REVIEW

**Comment by mostafasoufi** [comment]
Thank you for PR, please check out [this page](https://wp-sms-pro.com/gateways/add-new/) for adding a new gateway in the free version, otherwise, we're going to put this SMS gateway in the Pro pack.

Cheers.

**Comment by ismailh** [comment]
Please add this pro pack.

The Cyber Security Specialist
Ismail Hossain
System Administer & Forensic Investigator
*Eagle Eye Cyber Security*

**Comment by rezathriii** [comment]
Hello @ismailh,

Thank you for your request to add the SMSDone gateway to WP SMS Pro. We are happy to help and are committed to providing you with the best possible service.

We will work on adding this gateway to the plugin and will keep you informed about the process. In the meantime, if you have any questions or need additional assistance, please do not hesitate to contact us via the email address provided.

Thank you for your support and understanding.

Best regards,
Mohammadreza

**Comment by rezathriii** [comment]
Hello @ismailh,

Thank you for your request to add the SMSDone gateway to WP SMS Pro. We are happy to report that the gateway has been successfully added to the plugin and will be released in our next update.

We appreciate your patience and understanding as we worked on this request. If you have any further questions or need additional assistance, please do not hesitate to contact us.

Thank you for your support and we hope you enjoy the new SMSDone gateway in WP SMS Pro.


Best regards,
Mohammadreza

**Pull request closed without merging**
