### PR TITLE
api end points updated for mobtexting

### PR DESCRIPTION
**Pull request by laxman-ka**
Api has been updated to new version with bug fixes

### CODE REVIEW

**Comment by mostafasoufi** [comment]
Can you please do it in `development` branch?
@laxman-ka

**Comment by MHitMaN** [comment]
I've checked and the code was fine, but need to code on 'development' branch as u said.
@mostafasoufi 
Need to develop from me?

**Comment by mostafasoufi** [comment]
@MHitMaN Yes, please do it.

**Comment by MHitMaN** [comment]
Already Updated on Development branch!
Check the file :
https://github.com/veronalabs/wp-sms/blob/development/includes/gateways/class-wpsms-gateway-mobtexting.php

I'm thinking I did it earlier.

**Comment by MHitMaN** [comment]
Already Updated on Development branch!
Check the file :
https://github.com/veronalabs/wp-sms/blob/development/includes/gateways/class-wpsms-gateway-mobtexting.php

I'm thinking I did it earlier.
@mostafasoufi

**Pull request closed without merging**
